baseurl      = "https://hevispace.netlify.app/"
title        = "Welcome to Hevi Space"
languageCode = "en-us"
theme = "hugo-PaperMod"
paginate     = 10

[params]

  ShowBreadCrumbs = true
  ShowReadingTime = true
  defaultTheme = "auto"

  [params.header]
    desktopMode = "auto"
    mobileMode = "auto"

  [params.profileMode]
    enabled = true
    title = "Welcome Traveler \U0001F44B"
    subtitle = "Enjoy your stay!"
    imageUrl = "https://img.favpng.com/20/17/0/logo-graphic-design-png-favpng-rySDqpQs31nbJjyxWPidPvhxQ.jpg"
    #imageTitle = "<title of image as alt>"
    imageWidth = 120
    imageHeight = 120

  [[params.profileMode.buttons]]
    name = "Projects"
    url = "/posts"

  [[params.profileMode.buttons]]
    name = "Github"
    url = "https://github.com/"

  [[params.socialIcons]]
    name = "Instagram"
    url = "https://www.instagram.com/daniheevi"

  [[params.socialIcons]]
    name = "Tiktok"
    url = "https://gehscheissn.at"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hevi.Space"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Hevi.Space"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/space.jpg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
        identifier = "entries"
        name       = "Projects"
        url        = "/posts"
        weight = -110
  [[menu.main]]
        identifier = "tags"
        name       = "Tags"
        url        = "/tags"
        weight = -20
  [[menu.main]]
        identifier = "aboutme"
        name       = "About me"
        url        = "/myself"
        weight = -10
  [[menu.main]]
        identifier = "rl"
        name       = "RL Stuff"
        url        = "/rl"
        weight = -100
