baseurl      = "https://hevispace.netlify.app/"
title        = "Welcome to Hevi Space"
languageCode = "en-us"
theme = "hugo-PaperMod"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  ShowBreadCrumbs = true
  ShowReadingTime = true
  
  [params.homeInfoParams]
    Title = "Welcome Traveler!"
    Content = "Welcome to the space. Enjoy your stay!"
    #Image = posts/img/space.jgp

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Homespace of Hevi"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hevi.Space"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Hevi.Space"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/space.jpg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [menu]
  [[menu.main]]
        identifier = "entries"
        name       = "Projects"
        url        = "/posts"
        weight = -110
  [[menu.main]]
        identifier = "tags"
        name       = "Tags"
        url        = "/tags"
        weight = -20
  [[menu.main]]
        identifier = "aboutme"
        name       = "About me"
        url        = "/myself"
        weight = -10
  [[menu.main]]
        identifier = "rl"
        name       = "RL Stuff"
        url        = "/rl"
        weight = -100
